/* MCP endpoint — lets a Claude conversation read your training log and write to it.
 *
 * Off unless MCP_TOKEN is set, like the admin dashboard: a fresh instance exposes nothing.
 *
 * AUTH — the token is part of the URL: POST /api/mcp/<MCP_TOKEN>. A claude.ai custom
 * connector is configured with a URL and, optionally, OAuth credentials; it has nowhere to
 * put a custom header. So the URL itself is the credential, which makes it a secret with
 * all that implies:
 *   · anyone holding the URL has your whole log and can write to it — do not paste it
 *     anywhere you would not paste a password
 *   · nginx logs request paths by default, so web/nginx.conf and nginx.conf stop logging
 *     this one; check any proxy in front of them does the same
 *   · rotating it means changing MCP_TOKEN and re-adding the connector
 * OAuth would avoid all three and is the right answer for anything shared. This is the
 * simplest thing that is not "no auth at all", for one person's own instance.
 *
 * TRANSPORT — JSON-RPC 2.0 over a single POST, answered as JSON. No SSE: every tool here
 * answers immediately out of a file on disk, so there is nothing to stream, and a streaming
 * transport would be more moving parts for no gain.
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
// id -> name, generated by scripts/build-exercise-names.mjs. Without it a session reads as
// a list of opaque ids, which is useless to whatever is doing the coaching.
let NAMES = {};
try { NAMES = JSON.parse(fs.readFileSync(path.join(HERE, 'exercise-names.json'), 'utf8')); }
catch { console.error('mcp: exercise-names.json missing — run scripts/build-exercise-names.mjs'); }

// The version the client asks for is echoed back when it looks like a version at all: a
// simple server that implements one request/response shape is compatible across the
// revisions that shape has not changed in, and pinning one would break on the next.
const FALLBACK_PROTOCOL = '2025-06-18';

const TOKEN = process.env.MCP_TOKEN || '';
export const mcpEnabled = () => TOKEN.length >= 16;

/** Constant-time compare, so a wrong token cannot be found one character at a time. */
function tokenOk(given) {
  const a = Buffer.from(String(given || ''));
  const b = Buffer.from(TOKEN);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

/** The path this endpoint answers on, or null when it is not that path. */
export function mcpPath(pathname) {
  const m = /^\/api\/mcp\/(.+)$/.exec(pathname);
  return m ? m[1] : null;
}

/* ------------------------------------------------------------------ shaping -- */

const iso = d => new Date(d).toISOString().slice(0, 10);
const today = () => iso(Date.now());
const inWindow = (day, days, now) =>
  !days || new Date(day + 'T12:00:00').getTime() > now - days * 86400000;

const exName = (id, customEx) =>
  NAMES[id] || (customEx || []).find(c => c.id === id)?.n || id;

/** One logged set, in the terms it was logged in. */
function setOut(s) {
  const o = {};
  if (s.w) o.weight = s.w;
  if (s.r != null) o.reps = s.r;
  if (s.sec != null) o.seconds = s.sec;
  if (s.min != null) o.minutes = s.min;
  if (s.speed != null) o.speed = s.speed;
  if (s.rir != null) o.rir = s.rir;
  if (s.rpe != null) o.rpe = s.rpe;
  return o;
}

/**
 * A finished session. The prescription travels beside the sets — without it nothing on the
 * other end can say whether the session hit what it was asked for, which is the whole
 * signal a program gets adjusted on.
 */
function sessionOut(w, customEx) {
  return {
    date: w.d,
    routine: w.name,
    minutes: w.start && w.end ? Math.round((w.end - w.start) / 60000) : null,
    bodyweight: w.bw || null,
    volume: w.vol || null,
    personal_records: (w.prs || []).map(id => exName(id, customEx)),
    exercises: (w.entries || []).map(e => ({
      exercise: exName(e.id, customEx),
      target: e.target
        ? { sets: e.target.sets, reps: e.target.reps, seconds: e.target.sec, weight: e.target.weight }
        : null,
      sets: (e.sets || []).filter(s => s.done).map(setOut)
    }))
  };
}

// Absent fields are dropped rather than sent as null: the payload is read by a model, and
// a wall of "increment: null" is tokens spent saying nothing.
const compact = o => Object.fromEntries(Object.entries(o).filter(([, v]) => v != null));

function planOut(S) {
  const DAYS = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
  const week = {};
  DAYS.forEach((name, d) => {
    const r = (S.routines || []).find(x => x.id === (S.week || {})[d]);
    week[name] = r ? r.name : 'rest';
  });
  return {
    week,
    routines: (S.routines || []).map(r => compact({
      name: r.name,
      progression: r.prog,
      exercises: (r.ex || []).map(e => compact({
        exercise: exName(e.id, S.customEx),
        sets: e.sets, reps: e.reps, weight: e.weight,
        seconds: e.sec, minutes: e.min, speed: e.speed,
        reps_min: e.repsMin, reps_max: e.repsMax,
        progression: e.prog, increment: e.inc,
        per_side: e.side || undefined, superset: e.sg
      }))
    }))
  };
}

/* -------------------------------------------------------------------- tools -- */

const num = v => (Number.isFinite(+v) && +v > 0 ? +v : null);
const byDay = (a, b) => (a.d < b.d ? -1 : a.d > b.d ? 1 : 0);

// Maintenance as the app stores it. A profile written before the breakdown holds a bare
// number, which meant expenditure without training — a breakdown budgeting none.
const TDEE_PARTS = ['bmr', 'neat', 'other', 'sport'];
function tdeeOut(v) {
  if (v == null) return null;
  if (typeof v === 'number') return { bmr: 0, neat: 0, other: v, sport: 0, total: v };
  if (typeof v !== 'object') return null;
  const p = {};
  let total = 0;
  for (const k of TDEE_PARTS) { p[k] = Math.round(num(v[k]) || 0); total += p[k]; }
  return total > 0 ? { ...p, total } : null;
}
// An explicit 0 is a choice to trust the watch, not a missing value.
const watchTrim = S =>
  (Number.isFinite(+S.watchTrim) && +S.watchTrim >= 0 && +S.watchTrim <= 0.6 ? +S.watchTrim : 0.3);

export const TOOLS = [
  {
    name: 'get_training_log',
    description:
      'Read logged workouts, body weight, daily calorie/macro intake and daily activity for ' +
      'the last N days. Each exercise carries what the session prescribed alongside what was ' +
      'actually done, so you can tell whether it hit its target. `tdee` is the user\'s ' +
      'maintenance, broken into bmr / neat / other / sport with its total; `tdee.sport` is ' +
      'the training that total already budgets for, so a day\'s balance is ' +
      '(tdee.total + (activity.kcal - tdee.sport)) - intake.kcal — train as planned and it ' +
      'is simply total - intake. `activity.kcal` is already discounted by `watch_trim`, the ' +
      'share of the watch\'s active-energy reading the user does not trust (wrist devices ' +
      'read energy 20-40% high); `activity.kcal_raw` is what the watch actually said. Both ' +
      'tdee and a day with no intake logged can be null, and null means no balance rather ' +
      'than a balance of zero.',
    inputSchema: {
      type: 'object',
      properties: { days: { type: 'integer', description: 'Days back from today. 0 for everything. Default 30.' } }
    }
  },
  {
    name: 'get_plan',
    description: 'Read the current weekly plan: which routine runs on which day, and every exercise with its sets, reps, weight and progression rule.',
    inputSchema: { type: 'object', properties: {} }
  },
  {
    name: 'log_intake',
    description: 'Record a day of eating. Replaces that day if it was already logged. Omit a macro to leave it unrecorded.',
    inputSchema: {
      type: 'object',
      properties: {
        date: { type: 'string', description: 'YYYY-MM-DD. Defaults to today.' },
        kcal: { type: 'number' }, protein: { type: 'number' }, carbs: { type: 'number' }, fat: { type: 'number' }
      }
    }
  },
  {
    name: 'log_weight',
    description: 'Record a body-weight reading. Replaces that day if it was already logged.',
    inputSchema: {
      type: 'object',
      properties: { date: { type: 'string', description: 'YYYY-MM-DD. Defaults to today.' }, kg: { type: 'number' } },
      required: ['kg']
    }
  },
  {
    name: 'log_history',
    description:
      'Write a run of past days in one call — the retroactive import. Each day replaces what ' +
      'openGym holds for that date rather than adding to it, so re-sending a day is a ' +
      'correction, not a duplicate. Omit any field that was never recorded that day: an ' +
      'absent field is left alone, and a zero would be read as a real measurement.',
    inputSchema: {
      type: 'object',
      properties: {
        days: {
          type: 'array',
          description: 'One object per day. Every field except date is optional.',
          items: {
            type: 'object',
            properties: {
              date: { type: 'string', description: 'YYYY-MM-DD.' },
              kg: { type: 'number', description: 'Body weight.' },
              body_fat: { type: 'number', description: 'Percent.' },
              kcal: { type: 'number', description: 'Calories eaten.' },
              protein: { type: 'number' }, carbs: { type: 'number' }, fat: { type: 'number' },
              sport_kcal: { type: 'number', description: 'Energy burned by activity that day.' },
              steps: { type: 'integer' },
              sleep_hours: { type: 'number' }
            },
            required: ['date']
          }
        }
      },
      required: ['days']
    }
  },
  {
    name: 'propose_program',
    description:
      'Send a training program to the app. It is NOT applied here: it waits for the user to ' +
      'open openGym, where exercise names are matched against the 1324-exercise library and ' +
      'the whole resolution is shown before anything is written. Same shape as the app\'s ' +
      'paste-a-program format: { name, week: { monday: "Push", … }, routines: [ { name, ' +
      'progression, exercises: [ { name, sets, reps, weight } ] } ] }.',
    inputSchema: {
      type: 'object',
      properties: { program: { type: 'object', description: 'The program object.' } },
      required: ['program']
    }
  }
];

function callTool(name, args, S) {
  switch (name) {
    case 'get_training_log': {
      const days = args.days === 0 ? 0 : (num(args.days) || 30);
      const now = Date.now();
      return {
        from: days ? iso(now - days * 86400000) : null,
        to: today(),
        unit: S.unit || 'kg',
        weight_goal: S.targetW || null,
        intake_goal: S.nutriGoal || null,
        tdee: tdeeOut(S.tdee),
        watch_trim: watchTrim(S),
        activity: (S.health || []).filter(e => inWindow(e.d, days, now))
          .map(e => compact({
            date: e.d,
            kcal: e.kcal ? Math.round(e.kcal * (1 - watchTrim(S))) : null,
            kcal_raw: e.kcal || null,
            steps: e.steps, resting_hr: e.rhr
          })),
        sleep: (S.sleep || []).filter(e => inWindow(e.d, days, now))
          .map(e => compact({ date: e.d, bed: e.bed, wake: e.wake, awake_min: e.awake, hours: e.h, felt: e.q })),
        body_weight: (S.bodyweight || []).filter(b => inWindow(b.d, days, now)).map(b => ({ date: b.d, kg: b.w })),
        intake: (S.nutrition || []).filter(e => inWindow(e.d, days, now))
          .map(e => ({ date: e.d, kcal: e.kcal, protein: e.p, carbs: e.c, fat: e.f })),
        workouts: (S.workouts || []).filter(w => inWindow(w.d, days, now)).map(w => sessionOut(w, S.customEx))
      };
    }
    case 'get_plan':
      return planOut(S);

    case 'log_intake': {
      const d = /^\d{4}-\d{2}-\d{2}$/.test(args.date || '') ? args.date : today();
      const entry = { d, t: Date.now() };
      const map = { kcal: 'kcal', protein: 'p', carbs: 'c', fat: 'f' };
      for (const [from, to] of Object.entries(map)) { const v = num(args[from]); if (v) entry[to] = v; }
      const rest = (S.nutrition || []).filter(e => e.d !== d);
      // Every field blank clears the day, matching the app: that is how a mistake is undone.
      S.nutrition = (Object.keys(entry).length > 2 ? [...rest, entry] : rest).sort((a, b) => (a.d < b.d ? -1 : 1));
      return { ok: true, date: d, logged: Object.keys(entry).length > 2 };
    }
    case 'log_weight': {
      const kg = num(args.kg);
      if (!kg) throw new Error('kg must be a positive number');
      const d = /^\d{4}-\d{2}-\d{2}$/.test(args.date || '') ? args.date : today();
      const rest = (S.bodyweight || []).filter(b => b.d !== d);
      S.bodyweight = [...rest, { d, w: kg, t: Date.now() }].sort((a, b) => (a.d < b.d ? -1 : 1));
      return { ok: true, date: d, kg };
    }
    case 'log_history': {
      if (!Array.isArray(args.days) || !args.days.length) throw new Error('days must be a non-empty array');
      if (args.days.length > 2000) throw new Error('at most 2000 days per call');
      const put = (list, entry, keys) => {
        const rest = (list || []).filter(e => e.d !== entry.d);
        const kept = { d: entry.d, t: Date.now() };
        for (const k of keys) if (entry[k] != null) kept[k] = entry[k];
        // A day carrying nothing but its date is dropped, not stored as a row of blanks.
        return (Object.keys(kept).length > 2 ? [...rest, kept] : rest).sort(byDay);
      };
      let written = 0, skipped = 0;
      for (const d of args.days) {
        if (!/^\d{4}-\d{2}-\d{2}$/.test(d && d.date || '')) { skipped++; continue; }
        const day = d.date;
        let touched = false;

        const kg = num(d.kg), bf = num(d.body_fat);
        if (kg) {
          const ex = (S.bodyweight || []).find(b => b.d === day);
          S.bodyweight = put(S.bodyweight, { d: day, w: kg, bf: bf || (ex && ex.bf) || null }, ['w', 'bf']);
          touched = true;
        }
        const eaten = { d: day, kcal: num(d.kcal), p: num(d.protein), c: num(d.carbs), f: num(d.fat) };
        if (eaten.kcal || eaten.p || eaten.c || eaten.f) {
          const ex = (S.nutrition || []).find(e => e.d === day) || {};
          for (const k of ['kcal', 'p', 'c', 'f']) if (eaten[k] == null) eaten[k] = ex[k] != null ? ex[k] : null;
          S.nutrition = put(S.nutrition, eaten, ['kcal', 'p', 'c', 'f']);
          touched = true;
        }
        const sport = num(d.sport_kcal), steps = num(d.steps);
        if (sport || steps) {
          const ex = (S.health || []).find(e => e.d === day) || {};
          S.health = put(S.health, {
            d: day, kcal: sport || ex.kcal || null, steps: steps ? Math.round(steps) : ex.steps || null
          }, ['kcal', 'steps']);
          touched = true;
        }
        const slept = num(d.sleep_hours);
        if (slept && slept >= 0.5 && slept <= 16) { S.sleep = put(S.sleep, { d: day, h: slept }, ['h']); touched = true; }

        if (touched) written++; else skipped++;
      }
      return { ok: true, written, skipped };
    }
    case 'propose_program': {
      if (!args.program || typeof args.program !== 'object') throw new Error('program must be an object');
      if (!Array.isArray(args.program.routines) || !args.program.routines.length) {
        throw new Error('program.routines must be a non-empty array');
      }
      // Parked, not applied. Resolving names needs the exercise library and the matcher,
      // both of which live in the app — and a program rewriting someone's training deserves
      // a look before it lands, which is exactly what the app's review screen is.
      S.pendingProgram = { at: Date.now(), program: args.program };
      return {
        ok: true,
        status: 'waiting for the user to review it in openGym',
        routines: args.program.routines.length
      };
    }
    default:
      throw new Error(`unknown tool: ${name}`);
  }
}

const WRITES = new Set(['log_intake', 'log_weight', 'log_history', 'propose_program']);

/* ------------------------------------------------------------------ handler -- */

const rpc = (id, result) => ({ jsonrpc: '2.0', id, result });
const rpcError = (id, code, message) => ({ jsonrpc: '2.0', id, error: { code, message } });

/**
 * ctx: { readState(uid), writeState(uid, S), uid, readBody(req), json(res, code, obj) }
 */
export async function handleMcp(req, res, token, ctx) {
  if (!mcpEnabled() || !tokenOk(token)) return ctx.json(res, 404, { error: 'not found' });
  if (!ctx.uid) return ctx.json(res, 503, { error: 'no profile to serve — set MCP_UID' });

  let msg;
  try { msg = await ctx.readBody(req); } catch { return ctx.json(res, 400, rpcError(null, -32700, 'parse error')); }
  const id = msg && msg.id !== undefined ? msg.id : null;
  const method = msg && msg.method;

  // Notifications carry no id and expect no body — answering one with a result is a
  // protocol error, not a harmless extra.
  if (method && method.startsWith('notifications/')) { res.writeHead(202).end(); return; }

  if (method === 'initialize') {
    const asked = msg.params && msg.params.protocolVersion;
    return ctx.json(res, 200, rpc(id, {
      protocolVersion: /^\d{4}-\d{2}-\d{2}$/.test(asked || '') ? asked : FALLBACK_PROTOCOL,
      capabilities: { tools: { listChanged: false } },
      serverInfo: { name: 'openGym', version: '1.2.4' }
    }));
  }
  if (method === 'ping') return ctx.json(res, 200, rpc(id, {}));
  if (method === 'tools/list') return ctx.json(res, 200, rpc(id, { tools: TOOLS }));

  if (method === 'tools/call') {
    const name = msg.params && msg.params.name;
    const args = (msg.params && msg.params.arguments) || {};
    const S = ctx.readState(ctx.uid);
    if (!S) return ctx.json(res, 200, rpc(id, { isError: true, content: [{ type: 'text', text: 'no data for this profile yet' }] }));
    try {
      const out = callTool(name, args, S);
      if (WRITES.has(name)) {
        // The app takes the server's copy only when its timestamp is at least as new as the
        // local one, so a write that does not move _ts forward is a write the app ignores.
        S._ts = Date.now();
        ctx.writeState(ctx.uid, S);
      }
      return ctx.json(res, 200, rpc(id, { content: [{ type: 'text', text: JSON.stringify(out, null, 1) }] }));
    } catch (e) {
      // A tool that failed reports through the result, not as a transport error: the caller
      // is a model that can read the reason and try again.
      return ctx.json(res, 200, rpc(id, { isError: true, content: [{ type: 'text', text: String(e.message || e) }] }));
    }
  }

  return ctx.json(res, 200, rpcError(id, -32601, `method not found: ${method}`));
}
